- name: Build Servers on an Isolated Network
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    spawn_domain_name: amartus.io
  tasks:
    - name: Network create request
      local_action:
        module: rax_network
        credentials: ~/.raxpub
        label: test-net
        cidr: 192.168.3.0/24
        region: LON
        state: present

    - name: Server create request
      local_action:
        module: rax
        credentials: ~/.raxpub
        name: io.amartus.cloud.test.%04d
        flavor: 2
        image: bb02b1a3-bc77-4d17-ab5b-421d89850fca
        disk_config: manual
        networks:
          - public
          - test-net
        region: LON
        state: present
        count: 1
        exact_count: yes
        group: test
        wait: yes
        wait_timeout: 360
      register: rax
 
     - name: Adding forward DNS Entry
      local_action:
        module: rax_dns_record
        credentials: ~/.raxpub
        domain: "{{spawn_domain_name}}"
        name: "{{ item.name }}"
        data: "{{ item.rax_accessipv4 }}"
        type: A
      register: rax_dns_record
      with_items: rax.success
      when: rax.action == 'create'
      
    # - name: Add servers to in memory groups
    #   local_action:
    #     module: add_host
    #     hostname: "{{ item.name }}"
    #     ansible_ssh_host: "{{ item.rax_accessipv4 }}"
    #     ansible_ssh_pass: "{{ item.rax_adminpass }}"
    #     ansible_ssh_user: root
    #     rax_id: "{{ item.rax_id }}"
    #     groups: web,new_web
    #   with_items: rax.success
    #   when: rax.action == 'create'
      
    # - name: Adding forward DNS Entry
    #   local_action:
    #     module: rax_dns_record
    #     credentials: ~/.raxpub
    #     domain: "{{spawn_domain_name}}"
    #     name: "{{inventory_hostname}}"
    #     data: "{{ item.rax_accessipv4 }}"
    #     type: A
    #   register: rax_dns_record
