- name: Build Servers on an Isolated Network
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Network create request
      local_action:
        module: rax_network
        credentials: ~/.raxpub
        label: my-net
        cidr: 192.168.3.0/24
        region: LON
        state: present

    - name: Server create request
      local_action:
        module: rax
        credentials: ~/.raxpub
        name: ie.amartus.cloud.test.%04d
        flavor: 2
        image: dbb59b04-bd50-4eef-b05e-6a6451ef9bf2
        disk_config: manual
        networks:
          - public
          - my-net
        region: LON
        state: present
        count: 1
        exact_count: yes
        group: test
        wait: yes
        wait_timeout: 360
      register: rax
